const animeData = [
  // --- Te Bekijken (Status -1) ---
  { title: "Your Lie in April", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Orange", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "A Silent Voice", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "I want to eat your pancreas", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Inexpressive Kashiwada and Expressive Oota", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Umamusume: Pretty Derby", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "My Matchmaking Partner Is My Student, An Agg...", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Pseudo Harem", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Chitose Is in the Ramune Bottle", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Food for the Soul", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Makeine: Too Many Losing Heroines!", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "The Melancholy of Haruhi Suzumiya", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Classroom of the Elite", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Azumanga Daioh", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Teasing Master Takagi-san", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Clannad", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "The Ryuo's Work is Never Done!", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Tune In to the Midnight Heart", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "AHO-GIRL", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Ghost Stories", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "The Comic Artist and His Assistants", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Re:ZERO - Starting Life in Another World", status: -1, rating: 0, season: 1, episode: 1 },
  { title: "Spy x Family", status: -1, rating: 0, season: 1, episode: 1 },

  // --- Al Bekeken (Status 1) ---
  { title: "Rascal Does Not Dream", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Horimiya", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Oregairu SNAFU", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "KonoSuba", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "100 Girlfriends Who Really, Really Love You", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "High School DxD", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Kaguya-sama: Love is War", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Rascal Does Not Dream of Santa Claus", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Fruits Basket", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Toradora!", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "The Angel Next Door Spoils Me Rotten", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Alya Sometimes Hides Her Feelings in Russian", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "ReLIFE", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "The Fragrant Flower Blooms with Dignity", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "The Pet Girl of Sakurasou", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "My Dress-Up Darling", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "A Couple of Cuckoos", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Class President is a Maid!", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "And you thought there is never a girl online?", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Love, Chunibyo & Other Delusions!", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "The Iceblade Sorcerer Shall Rule the World", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Danganronpa: The Animation", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "My Little Sister Can't Be This Cute", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "The Dreaming Boy is a Realist", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Prison School", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Trinity Seven", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Akashic Records of Bastard Magic Instructor", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Masamune-kun's Revenge", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Shikimori's Not Just a Cutie", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "The Dangers in My Heart", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "More than a married couple, but not lovers.", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Golden Time", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Haganai: I don't have many friends", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Eromanga Sensei", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "SHIMONETA", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "The Genius Prince's Guide to Raising a Nation Out of Debt", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Don't Toy with Me, Miss Nagatoro", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Medaka Kuroiwa is Impervious to My Charms", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "My Girlfriend is Shobitch", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Bottom-Tier Character Tomozaki", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Can a Boy and Girl Friendship Hold Up?", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Hensuki: Are you willing to fall in love with a pervert, as long as she's a cutie?", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "My Little Monster", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Blue Box", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "The Children of Shiunji Family", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Gamers!", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Redo of Healer", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Kiss x Sis OVA", status: 1, rating: 0, season: 1, episode: 1 },
  { title: "Rent-a-Girlfriend", status: 1, rating: 0, season: 1, episode: 1 }
];

export { animeData };
